## IMPORTAR LAS LIBRERIAS

In [4]:
import numpy as np



In [5]:
A = np.array([(1,2,3),
             (4,5,6)])

B = np.array([(6,5,4),
             (3,2,1)])

In [6]:
C = A+B
print('Suma:\n',C)

Suma:
 [[7 7 7]
 [7 7 7]]


In [7]:
D = A-B
print('Resta:\n',D)

Resta:
 [[-5 -3 -1]
 [ 1  3  5]]


In [8]:
E=A*B
print('Punto a punto:\n',E)

Punto a punto:
 [[ 6 10 12]
 [12 10  6]]


In [9]:
A = np.array([(1,2),
             (3,4)])

B = np.array([(5,6),
             (7,8)])

C = np.dot(A,B)
D = A @ B
print('C:\n',C)
print('D:\n',D)

C:
 [[19 22]
 [43 50]]
D:
 [[19 22]
 [43 50]]


In [10]:
F = np.array([(1,2),
             (3,4)])

G= F.T
print('F:\n',F)
print('FT:\n',G)

F:
 [[1 2]
 [3 4]]
FT:
 [[1 3]
 [2 4]]


In [11]:
det = np.linalg.det(F)
print (det)

-2.0000000000000004


In [ ]:

#Utilizar la inversa de la matriz A
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
data = np.arange(1,13) #Aquí inicia en 1
print('Vector original: ', data)

#Reacomodar como:
M = data.reshape(3,4)
print('Matriz 3x4: \n',M)

Vector original:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matriz 3x4: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
I = np.eye(3)
print('Matriz de Uno: \n',I)

Matriz de Uno: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# MANEJO DE TABLAS CON PANDAS

In [35]:
import pandas as pd
import numpy as np 
import os

In [36]:
df = pd.read_csv('data_studentlist.csv', header= 'infer') #Para nombrar las listas con el nombre de la primer fila

In [37]:
df.head()

name gender  age  grade absence bloodtype  height  weight
0    Jared Diamond      M   23      3       Y         O   165.3    68.2
1   Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2     Brian Martin      M   24      4       N         B   175.0    80.1
3     David Hassel      M   23      3       N        AB   182.1    85.7
4  Clara Rodriquez      F   20      1       Y         A   168.0    49.5

In [38]:
df = df.rename(columns={
    "name": "NAME",
    "age": "AGE"
})
df.head ()

NAME gender  AGE  grade absence bloodtype  height  weight
0    Jared Diamond      M   23      3       Y         O   165.3    68.2
1   Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2     Brian Martin      M   24      4       N         B   175.0    80.1
3     David Hassel      M   23      3       N        AB   182.1    85.7
4  Clara Rodriquez      F   20      1       Y         A   168.0    49.5

In [39]:
df.columns = [col.upper() for col in df.columns]
df.head()

NAME GENDER  AGE  GRADE ABSENCE BLOODTYPE  HEIGHT  WEIGHT
0    Jared Diamond      M   23      3       Y         O   165.3    68.2
1   Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2     Brian Martin      M   24      4       N         B   175.0    80.1
3     David Hassel      M   23      3       N        AB   182.1    85.7
4  Clara Rodriquez      F   20      1       Y         A   168.0    49.5

In [40]:
df.columns = [col.lower() for col in df.columns]
df.head()

name gender  age  grade absence bloodtype  height  weight
0    Jared Diamond      M   23      3       Y         O   165.3    68.2
1   Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2     Brian Martin      M   24      4       N         B   175.0    80.1
3     David Hassel      M   23      3       N        AB   182.1    85.7
4  Clara Rodriquez      F   20      1       Y         A   168.0    49.5

In [41]:
df = df.add_prefix("prefix_")
df = df.add_suffix("_suf")

df.head()

prefix_name_suf prefix_gender_suf  prefix_age_suf  prefix_grade_suf  \
0    Jared Diamond                 M              23                 3   
1   Sarah O'Donnel                 F              22                 2   
2     Brian Martin                 M              24                 4   
3     David Hassel                 M              23                 3   
4  Clara Rodriquez                 F              20                 1   

  prefix_absence_suf prefix_bloodtype_suf  prefix_height_suf  \
0                  Y                    O              165.3   
1                  N                   AB              170.1   
2                  N                    B              175.0   
3                  N                   AB              182.1   
4                  Y                    A              168.0   

   prefix_weight_suf  
0               68.2  
1               53.0  
2               80.1  
3               85.7  
4               49.5

In [42]:
df.columns = ['NAME', 'GENDER' , 'AGE', 'GRADE', 'ABSENCE', 'BLOODTYPE', 'HEIGHT', 'WEIGHT']
df.head()

NAME GENDER  AGE  GRADE ABSENCE BLOODTYPE  HEIGHT  WEIGHT
0    Jared Diamond      M   23      3       Y         O   165.3    68.2
1   Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2     Brian Martin      M   24      4       N         B   175.0    80.1
3     David Hassel      M   23      3       N        AB   182.1    85.7
4  Clara Rodriquez      F   20      1       Y         A   168.0    49.5

In [43]:
df['IMC'] = 1000*df['WEIGHT']/df['HEIGHT']**2
df.head()


NAME GENDER  AGE  GRADE ABSENCE BLOODTYPE  HEIGHT  WEIGHT  \
0    Jared Diamond      M   23      3       Y         O   165.3    68.2   
1   Sarah O'Donnel      F   22      2       N        AB   170.1    53.0   
2     Brian Martin      M   24      4       N         B   175.0    80.1   
3     David Hassel      M   23      3       N        AB   182.1    85.7   
4  Clara Rodriquez      F   20      1       Y         A   168.0    49.5   

        IMC  
0  2.495966  
1  1.831754  
2  2.615510  
3  2.584407  
4  1.753827

In [44]:
df_left = df.loc[:, ['NAME','AGE', 'GENDER', 'ABSENCE']]
df_right = df.loc[:, ['NAME', 'BLOODTYPE', 'WEIGHT', 'HEIGHT']]


# Unir dataframes


In [ ]:
pd.merge(df_left,df_right, left_on="NAME", right_on="NAME", how="inner")

#left
#right
#outer


NAME  AGE GENDER ABSENCE BLOODTYPE  WEIGHT  HEIGHT
0      Jared Diamond   23      M       Y         O    68.2   165.3
1     Sarah O'Donnel   22      F       N        AB    53.0   170.1
2       Brian Martin   24      M       N         B    80.1   175.0
3       David Hassel   23      M       N        AB    85.7   182.1
4    Clara Rodriquez   20      F       Y         A    49.5   168.0
5   Jennifer Lorentz   21      F       N         O    52.0   162.0
6        Susan Clark   22      F       N         O    45.3   155.2
7    Margareth Jones   23      F       N         A    55.0   176.9
8       John Bertsch   23      M       N         B    64.2   178.5
9     Jake Timmerman   22      M       N         B    61.3   176.1
10     Joshua Connor   24      M       Y         O    62.0   167.1
11      John Matsuda   22      M       N        AB    75.8   180.0
12      Eddy Johnson   21      M       N         A    55.3   162.2
13  Rebecah Anderson   23      F       N         O    53.1   176.1
14      Linda Carter   22      F       N         B    45.2   158.2
15    Richard Swayze   24      M       Y         B    70.2   168.6
16       Andrew King   21      M       N         A    62.2   169.2